definitions:
  common.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Request Failure
        type: string
    type: object
  model.LoginUser:
    properties:
      Email:
        example: email
        type: string
      Password:
        example: password
        type: string
    required:
    - Email
    - Password
    type: object
info:
  contact:
    email: redaytowork@info.jp
    name: readytowork
    url: http://readytowork.jp
  license: {}
paths:
  /users/login:
    post:
      consumes:
      - application/json
      description: Login user by email and password
      parameters:
      - description: Login user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/model.LoginUser'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.HTTPError'
      summary: Login user
      tags:
      - users
swagger: "2.0"
